config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/sp1", to: "static_pages#sp1"
    get "/sp2", to: "static_pages#sp2"
    get "/sp3", to: "static_pages#sp3"
    get "/sp4", to: "static_pages#sp4"
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :order
  has_many :detail_bills
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
end

app/models/detail_bill.rb
class DetailBill < ApplicationRecord
  belongs_to :bill
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  has_one :bill
  belongs_to :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :detail_bills
  has_many :order_products
  has_many :product_categories
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true,
                    length: {maximum: Settings.max_length_email},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :name,  presence: true, length: {maximum: Settings.max_length_name}
  validates :password, presence: true,
             length: {minimum: Settings.min_length_pass}

  has_secure_password

  private

  def email_downcase
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = if I18n.available_locales.include?(locale)
                    locale
                  else
                    I18n.default_locale
                  end
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "ok"
      redirect_to @user
    else
      flash[:danger] = t "error"
      render :new
    end
  end

  def show
    @user = User.find_by id: params[:id]

    return if @user
    flash[:fails] = t "fails"
    redirect_to signup_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t(".TopMen")
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/users_helper.rb
module UsersHelper
   def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end
  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <b><%= t ".TopMen" %></b>
    <%= t "by" %> <b>Hung |Hieu </b>
  </small>
  <nav>
    <ul>
      <li><%= link_to Settings.phone_number, '#', class:"fa fa-phone-square" %></li>
      <li><%= link_to Settings.gmail, '#',class:"fa fa-envelope" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to image_tag("rails.png", alt: "logo", :size => "100x60"), root_path, id: "logo" %>
    <div class="row">
    <nav class="header_above">
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t("home"), root_path %></li>
          <li><%= link_to t("help"), help_path %></li>
          <li><%= link_to t("login"), '#', class:'fa fa-user' %></li>
          <li><%= link_to t("sign_up"), signup_path, class:"fa fa-lock" %></li>
          <a>
          <input type="text" ="search" placeholder="Search..">
          </a>
        <li><%= link_to t("english"), locale:"en" %></li>
        <li><%= link_to t("vietnamese"), locale:"vi" %></li>

        <div style="float:right;width:10px:height:93px;">
        <div id="shopcart">
              <%= link_to image_tag("shopcart.png", alt: "shopcart", :size => "45x45"), id: "shopcart" %>

        </div>
      </ul>
        </ul>
      </nav>
    </div>

  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
                                              "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
<%= render "layouts/shim" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>      
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    <%= t ".content1" %> <%= pluralize @user.errors.count, t(".content2") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/help.html.erb
<% provide :title, t(".help") %>
<h1><%= t ".help" %></h1>
<p>
  <%= t ".help_me" %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".home") %>
<h1>
  <%= image_tag("h3.png", alt: "h3", :size => "1000x400")%>
</h1>
<h2>
  <b><%= t ".featured products" %></b>
</h2>
<div class="container">
 <div class="row">
    <div class="col-md-3">
      <%= link_to image_tag("h4.png", alt: "h4", :size => "250x150"), src="sp1", id: "h4" %>
      <p>SP 01</p>
    </div>

    <div class="col-md-3">
    <%= link_to image_tag("h5.png", alt: "h5", :size => "250x150"), src="sp2", id: "h5" %>
    <p>SP 02</p>
  </div>

  <div class="col-md-3">
    <%= link_to image_tag("h6.png", alt: "h6", :size => "250x150"), src="sp3", id: "h6" %>
    <p>SP 03</p>
  </div>

  <div class="col-md-3">
    <%= link_to image_tag("h7.png", alt: "h7", :size => "250x150"), src="sp4", id: "h7" %>
    <p>SP 04</p>
  </div>

app/views/static_pages/sp1.html.erb
<% provide :title, t(".sp1") %>
<h1><%= t ".sp1" %></h1>

<div class="col-md-3">
<%= link_to image_tag("h4.png", alt: "h4", :size => "250x150"), id: "h4" %>
<p>SP 01</p>
</div>
Áo Sơ mi chấm sao

</div>

app/views/static_pages/sp2.html.erb
<% provide :title, t(".sp2") %>
<h1><%= t ".sp2" %></h1>

<div class="col-md-3">
<%= link_to image_tag("h5.png", alt: "h5", :size => "250x150"), id: "h5" %>
<p>SP 02</p>
</div>
Áo kaki đen 
</div>

app/views/static_pages/sp3.html.erb
<% provide :title, t(".sp3") %>
<h1><%= t ".sp3" %></h1>

<div class="col-md-3">
<%= link_to image_tag("h6.png", alt: "h6", :size => "250x150"), id: "h6" %>
<p>SP 03</p>
</div>
Áo sơ mi trắng 
</div>

app/views/static_pages/sp4.html.erb
<% provide :title, t(".sp4") %>
<h1><%= t ".sp4" %></h1>

<div class="col-md-3">
<%= link_to image_tag("h7.png", alt: "h7", :size => "250x150"), id: "h7" %>
<p>SP 04</p>
</div>
Áo sơ mi cổ tròn
</div>

app/views/users/new.html.erb
<% provide :title, t("sign_up") %>
<h1><%= t "sign_up" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :name, t("name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, t("email") %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :phone, t("phone") %>
      <%= f.phone_field :phone, class: "form-control" %>

      <%= f.label :password, t("pass") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t("confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    </div>
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>